version: '3.8'

services:
  ldap_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classos_ldap_test
    environment:
      - AD_HOST=${AD_HOST:-host.docker.internal}
      - AD_PORT=${AD_PORT:-636}
      - AD_BASE_DN=${AD_BASE_DN:-}
      - AD_BIND_USER=${AD_BIND_USER:-}
      - AD_BIND_PASS=${AD_BIND_PASS:-}
      - AD_USE_TLS=${AD_USE_TLS:-true}
    networks:
      - test_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - test

  ldap_debug:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classos_ldap_debug
    environment:
      - AD_HOST=${AD_HOST:-host.docker.internal}
      - AD_PORT=${AD_PORT:-636}
      - AD_BASE_DN=${AD_BASE_DN:-}
      - AD_BIND_USER=${AD_BIND_USER:-}
      - AD_BIND_PASS=${AD_BIND_PASS:-}
      - AD_USE_TLS=${AD_USE_TLS:-true}
    networks:
      - test_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["sh"]
    stdin_open: true
    tty: true
    profiles:
      - debug

networks:
  test_network:
    driver: bridge